### ISSUE TITLE
qpois gives incorrect values when rate different from 10

### ISSUE THREAD

**Issue by grizant** [kthohr/stats#7]
Hello,

Thanks for your work on this project. I'm trying to use the qpois function with different rates. The output is correct when rate=10 in the test cases, but if say the rate is 1135, the function returns all 66. See the test output below:

*** qpois: begin tests. ***

qpois(0.00): 66.00000. Success = 0
qpois(0.00): 66.00000. Success = 0
qpois(0.00): 66.00000. Success = 0
qpois(0.01): 66.00000. Success = 0
qpois(0.07): 66.00000. Success = 0
qpois(0.33): 66.00000. Success = 0
qpois(0.58): 66.00000. Success = 0
qpois(0.92): 66.00000. Success = 0
qpois(1.00): 66.00000. Success = 0

Thank you for any guidance on correcting this. Let me know if you need help debugging.

**Comment by kthohr** [comment]
Most likely due to integer overflow in the calculation of `ppois`. These cases are handled by an incomplete gamma function representation, but I have yet to implement a series approximation to handle large input values. Should look roughly like a skew normal distribution. 

Thanks pointing this out. I'll try to implement a new version in the coming days.

**Comment by kthohr** [comment]
New version is in the master branch. Can you re-run your tests and let me know if anything breaks?
